language: bash

os:
- linux

env:
  - BASHVER=
  - BASHVER=3.2
  - BASHVER=4.0
  - BASHVER=4.1
  - BASHVER=4.2
  - BASHVER=4.3
  - BASHVER=4.4

services:
  - docker

script:
- |
  if [[ "$TRAVIS_OS_NAME" == 'linux' && -n "$BASHVER" ]]; then
    docker build --build-arg bashver=${BASHVER} --tag bats/bats:bash-${BASHVER} https://github.com/bats-core/bats-core.git
    printf "FROM bats/bats:bash-${BASHVER}\nWORKDIR /code\nENTRYPOINT []\nCMD [\".\/run_tests.sh\"]" > Dockerfile
    docker build --tag tester:bash-${BASHVER} .
    docker run -it -v `pwd`:/code tester:bash-${BASHVER}
  fi

notifications:
  email:
    on_success: never